#!/bin/sh

CreateCTag()
{
    if [[ $# -lt 2 ]]
    then
        echo "invalid params "$*
        exit 1
    fi

    code_dir_list=$1
    ctags_file=$2
    ctags_params="--extra=f"
    if [[ $# -ge 3 ]] 
    then
        ctags_params="$ctags_params $3"
    fi
    tmp_file=/tmp/c_tags_to_file

    find $code_dir_list -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.cc" > $tmp_file && ctags $ctags_params -L $tmp_file -f $ctags_file

    if [[ $? == 0 ]]
    then
        echo "ctags \"$code_dir_list\" \"$ctags_params\" > \"$ctags_file\" succ"
    else
        echo "ctags \"$code_dir_list\" \"$ctags_params\" > \"$ctags_file\" failed"
    fi
}

if [[ $# -lt 2 ]]
then
    echo "Usage: createctags \"code_dir_list\" \"ctags_file\" \"ctag_params\""
    exit 1
fi

CreateCTag "$1" "$2" "$3"
