#!/bin/sh
aimindex=$1
arg=''
for (( i=2; i<=$#; i++  )); do
    eval tmparg=\$$i
    arg="$arg $tmparg"
done

if [[ $aimindex -lt 0 ]]; then
    totalnum=`/bin/gr $arg | wc -l`
    aimindex=$((totalnum+aimindex+1))
fi
if [[ $aimindex == 'a' ]]; then
    /usr/bin/xvim -p `/bin/gr $arg | awk -F: '{print $1}' | sort -u | tr '\n' ' '`
else
    /usr/bin/xvim `/bin/gr $arg | awk -F: '{if(NR==aimindex) print $1,"+"$2}' aimindex="$aimindex"`
fi
