#!/bin/sh
aimindex=$1
aimstr=$2
dirstr=$3
if [[ -z $dirstr ]]; then dirstr='.'; fi
#把shell变量传入awk的方式之一: aimindex="$aimindex"
if [[ $aimindex -lt 0 ]]; then
    totalnum=`grep -rn --color "$aimstr" $dirstr | grep -v ".svn" | grep -v './tags' | grep -v ".swp " | grep -v "./ctags" | grep -v "Binary file" | wc -l`
    aimindex=$((totalnum+aimindex+1))
fi
if [[ $aimindex == 'a' ]]; then
    rt=`grep -rn --color "$aimstr" $dirstr | grep -v ".svn" | grep -v './tags' | grep -v ".swp " | grep -v "./ctags" | grep -v "Binary file" | awk -F: '{print $1}'| sort -u| tr '\n' ' ' `
    vim --cmd ":colorscheme desert" --cmd ":set number" --cmd "set tabstop=4 shiftwidth=4 expandtab" -p $rt
else
    rt=`grep -rn --color "$aimstr" $dirstr | grep -v ".svn" | grep -v './tags' | grep -v ".swp " | grep -v "./ctags" | grep -v "Binary file" | awk -F: '{if(NR==aimindex) print $1,$2}' aimindex="$aimindex"`
    fname=`echo "$rt"| awk '{print $1}'`
    line=`echo "$rt"| awk '{print $2}'`
    vim --cmd ":colorscheme desert" --cmd ":set number" --cmd "set tabstop=4 shiftwidth=4 expandtab" $fname +$line
fi
